/* generated configuration header file - do not edit */
#ifndef R_XSPI_HYPER_CFG_H_
#define R_XSPI_HYPER_CFG_H_
#define XSPI_HYPER_CFG_PARAM_CHECKING_ENABLE      (BSP_CFG_PARAM_CHECKING_ENABLE)
#define XSPI_HYPER_CFG_UNIT_0_PREFETCH_FUNCTION   (0)
#define XSPI_HYPER_CFG_UNIT_1_PREFETCH_FUNCTION   (0)
#define XSPI_HYPER_CFG_UNIT_0_IOVOLTAGE           (0)
#define XSPI_HYPER_CFG_UNIT_1_IOVOLTAGE           (0)
#define XSPI_HYPER_CFG_UNIT_0_CS_0_END_ADDRESS    (0x47FFFFFF)
#define XSPI_HYPER_CFG_UNIT_0_CS_1_START_ADDRESS  (0x48000000)
#define XSPI_HYPER_CFG_UNIT_0_CS_1_END_ADDRESS    (0x4FFFFFFF)
#define XSPI_HYPER_CFG_UNIT_1_CS_0_END_ADDRESS    (0x53FFFFFF)
#define XSPI_HYPER_CFG_UNIT_1_CS_1_START_ADDRESS  (0x58000000)
#define XSPI_HYPER_CFG_UNIT_1_CS_1_END_ADDRESS    (0x5BFFFFFF)
#endif /* R_XSPI_HYPER_CFG_H_ */
