/***********************************************************************************************************************
 * Copyright [2020-2024] Renesas Electronics Corporation and/or its affiliates.  All Rights Reserved.
 *
 * This software and documentation are supplied by Renesas Electronics Corporation and/or its affiliates and may only
 * be used with products of Renesas Electronics Corp. and its affiliates ("Renesas").  No other uses are authorized.
 * Renesas products are sold pursuant to Renesas terms and conditions of sale.  Purchasers are solely responsible for
 * the selection and use of Renesas products and Renesas assumes no liability.  No license, express or implied, to any
 * intellectual property right is granted by Renesas.  This software is protected under all applicable laws, including
 * copyright laws. Renesas reserves the right to change or discontinue this software and/or this documentation.
 * THE SOFTWARE AND DOCUMENTATION IS DELIVERED TO YOU "AS IS," AND RENESAS MAKES NO REPRESENTATIONS OR WARRANTIES, AND
 * TO THE FULLEST EXTENT PERMISSIBLE UNDER APPLICABLE LAW, DISCLAIMS ALL WARRANTIES, WHETHER EXPLICITLY OR IMPLICITLY,
 * INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NONINFRINGEMENT, WITH RESPECT TO THE
 * SOFTWARE OR DOCUMENTATION.  RENESAS SHALL HAVE NO LIABILITY ARISING OUT OF ANY SECURITY VULNERABILITY OR BREACH.
 * TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT WILL RENESAS BE LIABLE TO YOU IN CONNECTION WITH THE SOFTWARE OR
 * DOCUMENTATION (OR ANY PERSON OR ENTITY CLAIMING RIGHTS DERIVED FROM YOU) FOR ANY LOSS, DAMAGES, OR CLAIMS WHATSOEVER,
 * INCLUDING, WITHOUT LIMITATION, ANY DIRECT, CONSEQUENTIAL, SPECIAL, INDIRECT, PUNITIVE, OR INCIDENTAL DAMAGES; ANY
 * LOST PROFITS, OTHER ECONOMIC DAMAGE, PROPERTY DAMAGE, OR PERSONAL INJURY; AND EVEN IF RENESAS HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH LOSS, DAMAGES, CLAIMS OR COSTS.
 **********************************************************************************************************************/

#include "hal_data.h"
#ifdef USE_HRAM
#include "hram_sample.h"
#endif

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event) BSP_PLACE_IN_SECTION(".warm_start");
FSP_CPP_FOOTER

#if 0  /* SDRAM is initialized by the Loader (SSBL) project, not by the App. */
static void bsp_sdram_init (void);
#endif

#define BSC_PROTECT_KEY     (0xa55a0000)

#ifdef USE_ETHERNET
void handle_error (fsp_err_t err);
void timer_callback (timer_callback_args_t * p_args);
uint64_t Get_Time_Stamp(void);
#if (defined(USE_RTOS) && !defined(RZT2_RSK_PNS))
#include "semphr.h"
extern  SemaphoreHandle_t uart_rx_semaphore;    // Semaphore to block task to wait for new UART RX
extern StaticSemaphore_t uart_rx_semaphorebuffer;
#endif
int64_t TimetStamp = 0;   /* countup integration time (ms) */
int32_t time_milli = 0;
int32_t time_sec   = 0;
#endif /* USE_ETHERNET */

#ifdef USE_HRAM
fsp_err_t hram_init(void);
fsp_err_t hram_trans(hram_transfer_t trans);
fsp_err_t check_ints(void);
uint16_t swap16(uint16_t value);
#endif

#if defined(__ICCARM__)
 #pragma section="SYSTEM_PRG_RBLOCK"
 #pragma section="SYSTEM_PRG_WBLOCK"
 #pragma section="SYSTEM_DATA_RBLOCK"
 #pragma section="SYSTEM_DATA_WBLOCK"
 #pragma section="EXTRAMNC_BLOCK"
 #pragma section="HEAP4_BLOCK"
 #pragma section="HEAP_BLOCK"
 #pragma section="EXT_DATA_ZBLOCK"

 #define SYSTEM_PRG_SRC_START     __section_begin("SYSTEM_PRG_RBLOCK")
 #define SYSTEM_PRG_DST_START     __section_begin("SYSTEM_PRG_WBLOCK")
 #define SYSTEM_PRG_SIZE          __section_size("SYSTEM_PRG_WBLOCK")
 #define SYSTEM_DATA_SRC_START    __section_begin("SYSTEM_DATA_RBLOCK")
 #define SYSTEM_DATA_DST_START    __section_begin("SYSTEM_DATA_WBLOCK")
 #define SYSTEM_DATA_SIZE         __section_size("SYSTEM_DATA_WBLOCK")
 #define EXTRAMNC_BLOCK_START     __section_begin("EXTRAMNC_BLOCK")
 #define EXTRAMNC_BLOCK_END       __section_end("EXTRAMNC_BLOCK")
 #define HEAP_BLOCK_START         __section_begin("HEAP4_BLOCK")
 #define HEAP_BLOCK_END           __section_end("HEAP_BLOCK")
 #define EXTBSS_BLOCK_START       __section_begin("EXT_DATA_ZBLOCK")
 #define EXTBSS_BLOCK_END         __section_end("EXT_DATA_ZBLOCK")
#endif                                 // __ICCARM__

void bsp_clear_external_bss_sections(void);
void bsp_copy_to_external_ram(void);

extern void bsp_bss_init_multibyte (volatile uintptr_t *, volatile uintptr_t);
extern void bsp_copy_multibyte(uintptr_t *, uintptr_t *, uintptr_t);

/*******************************************************************************************************************//**
 * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */
#ifndef USE_ETHERNET
#if INTCPU0_ENABLE

    /* Define the units to be used with the software delay function */
    const bsp_delay_units_t bsp_delay_units = BSP_DELAY_UNITS_MILLISECONDS;

    /* Set the blink frequency (must be <= bsp_delay_units */
    const uint32_t freq_in_hz = 2;

    /* Calculate the delay in terms of bsp_delay_units */
    const uint32_t delay = bsp_delay_units / freq_in_hz;

    /* LED type structure */
    bsp_leds_t leds = g_bsp_leds;

    /* If this board has no LEDs then trap here */
    if (0 == leds.led_count)
    {
        while (1)
        {
            ;                          // There are no LEDs on this board
        }
    }

    /* GIC settings for CPUINT0. */
    R_BSP_IrqCfgEnable(VECTOR_NUMBER_CPUINT0, 1, NULL);

    /* Enable interrupt. */
    __asm volatile ("cpsie i");

    while (1)
    {
        /* Generate INTCPU0. */
        R_ICU0->NS_SWINT = 0x00000001U;

        /* Delay */
        R_BSP_SoftwareDelay(delay, bsp_delay_units);
    }

#else
    /* Define the units to be used with the software delay function */
    const bsp_delay_units_t bsp_delay_units = BSP_DELAY_UNITS_MILLISECONDS;

    /* Set the blink frequency (must be <= bsp_delay_units */
    const uint32_t freq_in_hz = 2;

    /* Calculate the delay in terms of bsp_delay_units */
    const uint32_t delay = bsp_delay_units / freq_in_hz;

    /* LED type structure */
    bsp_leds_t leds = g_bsp_leds;

    /* If this board has no LEDs then trap here */
    if (0 == leds.led_count)
    {
        while (1)
        {
            ;                          // There are no LEDs on this board
        }
    }

    /* Holds level to set for pins */
    bsp_io_level_t pin_level = BSP_IO_LEVEL_LOW;

    while (1)
    {
        /* This code uses BSP IO functions to show how it is used.*/
        R_BSP_PinAccessEnable();

        /* Update all board LEDs */
        for (uint32_t i = 0; i < leds.led_count; i++)
        {
            /* Get pin to toggle */
            uint32_t pin = leds.p_leds[i];

            /* Write to this pin */
            R_BSP_PinWrite((bsp_io_port_pin_t) pin, pin_level);
        }

        /* Protect PFS registers */
        R_BSP_PinAccessDisable();

        /* Toggle level for next write */
        if (BSP_IO_LEVEL_LOW == pin_level)
        {
            pin_level = BSP_IO_LEVEL_HIGH;
        }
        else
        {
            pin_level = BSP_IO_LEVEL_LOW;
        }

        /* Delay */
        R_BSP_SoftwareDelay(delay, bsp_delay_units);
    }
#endif
#else
#ifndef RZT2_RSK_PNS
    fsp_err_t err;

    /* Open the transfer instance with initial configuration. */
    err = R_SCI_UART_Open(&g_uart0_ctrl, &g_uart0_cfg);
    handle_error(err);

    r_sci_uart_baud_example();


    err = R_CMTW_Open(&g_timer0_ctrl, &g_timer0_cfg);
    handle_error(err);

    __asm volatile ("cpsie i");

    /* Start the timer. */
    (void) R_CMTW_Start(&g_timer0_ctrl);

    /* Enable compare match function. */
    (void) R_CMTW_Enable(&g_timer0_ctrl);
#endif
#endif
}

#ifdef USE_ETHERNET
/* Example callback called when timer expires. */
void timer_callback (timer_callback_args_t * p_args)
{
    TimetStamp++;   /* countup integration time (ms) */

    time_milli++;
    if( 1000 > time_milli)
    {
        return;
    }
    time_milli = 0;
    time_sec++;

#ifndef USE_RTOS
    if (TIMER_EVENT_CYCLE_END == p_args->event)
    {
        /* Add application code to be called periodically here. */
        /* LED type structure */
        bsp_leds_t leds = g_bsp_leds;

        /* This code uses BSP IO functions to show how it is used.*/
        R_BSP_PinAccessEnable();

        /* Update all board LEDs */
        for (uint32_t i = 0; i < leds.led_count; i++)
        {
            /* Get pin to toggle */
            uint32_t pin = leds.p_leds[i];

            /* Write to this pin */
            R_BSP_PinWrite((bsp_io_port_pin_t) pin, pin_level);
        }

        /* Protect PFS registers */
        R_BSP_PinAccessDisable();

        /* Toggle level for next write */
        if (BSP_IO_LEVEL_LOW == pin_level)
        {
            pin_level = BSP_IO_LEVEL_HIGH;
        }
        else
        {
            pin_level = BSP_IO_LEVEL_LOW;
        }
    }
#endif
}

uint64_t Get_Time_Stamp(void)
{
  return TimetStamp;
}
void handle_error (fsp_err_t err)
{
  ;
}

#endif

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
/* QSPI Quad-Enable bootstrap (formerly here) has been moved into the Loader
 * project (RZN2L_bsp_xspi0bootx1_loader/src/hal_entry.c). The Application
 * keeps only the g_qspi0 instance which is used at runtime by the PROFINET
 * stack (profinet_sdk/src/pns/rtos/rtos_rzt2_qspi_flash.c). */
void R_BSP_WarmStart (bsp_warm_start_event_t event)
{
    /* NOTE: BSP_WARM_START_POST_LOADER hook is handled by the Loader
     * project (RZN2L_bsp_xspi0bootx1_loader). It performs board pin setup,
     * external SDRAM/HyperRAM init and (when needed) QSPI Quad-Enable.
     * The application opens its own IOPORT control block after its external
     * RAM data/BSS sections are initialized. */

    if (BSP_WARM_START_RESET == event)
    {
    	/* Pre clock initialization */
    }
    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

#if BSP_FEATURE_DDR_SUPPORTED
 #if (1 == BSP_CFG_DDR_INIT_ENABLE)

        /* Initialize the DDR settings. */
        bsp_ddr_init();
 #endif
#endif

        /* External RAM (SDRAM/HyperRAM) and the App image sections are
         * initialized by the Loader (SSBL) before jumping to the application.
         * Only clear runtime zero-init/no-init work areas here. */

        bsp_clear_external_bss_sections();

    #if 0
        /* Loader manifest already copied SYSTEM_PRG/DATA_RBLOCK to
         * SYSTEM_PRG/DATA_WBLOCK before jumping to the App. */
        bsp_copy_to_external_ram();
    #endif

        if (NULL != g_bsp_pin_cfg.p_extend)
        {
            R_IOPORT_Open(&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);
        }
    }
}

#if 0  /* SDRAM init is done in the Loader project; kept here for reference. */
/*******************************************************************************************************************//**
 * @brief      Setup SDRAM controller
 *
 * @param[in]  void         none
 **********************************************************************************************************************/
static void bsp_sdram_init (void)
{
    volatile uint32_t val;

    R_RWP_S->PRCRS  = 0x0000A50F;
    R_RWP_NS->PRCRN = 0x0000A50F;

    /* NOTE: Port setting and CKIO configuration should have been done before */

    // Configure clock frequency
    val = R_SYSC_NS->SCKCR;
    val &= ~(7<<16);
    //val |=  (6<<16);	// CKIO clock: 25MHz
    val |=  (1<<16);	// CKIO clock: 66.7MHz
    R_SYSC_NS->SCKCR = val;

    /* Enable BSC and CKIO module */
    val = R_SYSC_NS->MSTPCRA;
    val &= ~(1<<0);
    R_SYSC_NS->MSTPCRA = val;
    val = R_SYSC_NS->MSTPCRA;        // dummy read: step1

    // Enable CKIO module
    val = R_SYSC_NS->MSTPCRD;
    val &= ~(1<<11);
    R_SYSC_NS->MSTPCRD = val;
    val = R_SYSC_NS->MSTPCRD;        // dummy read: step1

    R_RWP_NS->PRCRN = 0x0000A500;
    R_RWP_S->PRCRS  = 0x0000A500;

    /* Wait */
	val = R_BSC->CSnBCR[3];        // dummy read: step2
	val = R_BSC->CSnBCR[3];        // dummy read: step2
	val = R_BSC->CSnBCR[3];        // dummy read: step2
	val = R_BSC->CSnBCR[3];        // dummy read: step2
	val = R_BSC->CSnBCR[3];        // dummy read: step2


    /* SDRAM:W9825G6KH-6 */
    /* Row address: A0-A12. Column address: A0-A8. */
	val = ( 2 <<  9)	// BSZ: data bus witdh: 16-bits
	 	| ( 1 << 11)	// Reserved
	 	| ( 4 << 12)	// TYPE: SDRAM
	 	| ( 0 << 16)	// IWRRS: Idle State Insertion between Read-Read Cycles in the Same CS Space
	 	| ( 0 << 19)	// IWRRD: Idle State Insertion between Read-Read Cycles in Different CS Spaces
	 	| ( 0 << 22)	// IWRWS: Idle State Insertion between Read-Write Cycles in the Same CS Space
	 	| ( 0 << 25)	// IWRWD: Idle State Insertion between Read-Write Cycles in Different CS Spaces
	 	| ( 0 << 28);	// IWW: Idle Cycles between Write-Read Cycles and Write-Write Cycles
    R_BSC->CSnBCR[3] = val;

    /* Wait cycle */
	val = ( 2 <<  0)	// WTRC: Number of Idle states frmo REF Command/Self-refresh relase to ACTV/REF/MRS command
	 	| ( 2 <<  3)	// TRWL: Number of Auto-precharge startup Wait Cycle
	 	| ( 1 <<  7)	// A3CL: CAS Latency: 2
	 	| ( 1 << 10)	// WTRCD: Number of Waits between ACTV command and READ/WRIT command
	 	| ( 1 << 13);	// WTRP: Number of Auto-precharge completion wait states
        R_BSC->CS3WCR_1 = val;

    /* Wait */
	val = R_BSC->CSnBCR[2];        // dummy read: step2
	val = R_BSC->CSnBCR[2];        // dummy read: step2
	val = R_BSC->CSnBCR[2];        // dummy read: step2
	val = R_BSC->CSnBCR[2];        // dummy read: step2
	val = R_BSC->CSnBCR[2];        // dummy read: step2


    /* SDRAM:W9825G6KH-6 */
    /* Row address: A0-A12. Column address: A0-A8. */
	val = ( 2 <<  9)	// BSZ: data bus witdh: 16-bits
	 	| ( 1 << 11)	// Reserved
	 	| ( 4 << 12)	// TYPE: SDRAM
	 	| ( 0 << 16)	// IWRRS: Idle State Insertion between Read-Read Cycles in the Same CS Space
	 	| ( 0 << 19)	// IWRRD: Idle State Insertion between Read-Read Cycles in Different CS Spaces
	 	| ( 0 << 22)	// IWRWS: Idle State Insertion between Read-Write Cycles in the Same CS Space
	 	| ( 0 << 25)	// IWRWD: Idle State Insertion between Read-Write Cycles in Different CS Spaces
	 	| ( 0 << 28);	// IWW: Idle Cycles between Write-Read Cycles and Write-Write Cycles
    R_BSC->CSnBCR[2] = val;

    /* Wait cycle */
    val = ( 1 <<  7)	// A3CL: CAS Latency: 2
	 	| ( 1 << 10);	// Reserved 1

    R_BSC->CS2WCR_1 = val;

    /* SDRAM control */
    R_BSC->SDCR = 0x00110811;		// auto-refresh, auto-precharge mode, Col 9-bits, Row 13-bits

    /* Refresh setting for SDRAM */
    R_BSC->RTCOR = BSC_PROTECT_KEY
                 | ( 29 <<  0);        // Refresh Time: 29 counts
    R_BSC->RTCSR = BSC_PROTECT_KEY
                 | (  0 <<  7)         // Compare match Flag: clear
                 | (  0 <<  6)         // Compare match interrupt enable: Disabled
                 | (  2 <<  3)         // Refresh timer count clock: CKIO/16
                 | (  0 <<  0);        // Refresh count: 1 time

    /* wait 200us*/
    R_BSP_SoftwareDelay(200, BSP_DELAY_UNITS_MICROSECONDS);

    /* Power-on Sequence */
    /* Set mode register of SDRAM. needs wait for 2 SDRAM clock after set. */
    *((uint16_t *)0x80212040) = 0x0000;   // Burst length=1, Sequential, CL=2, Burst read and burst write
    *((uint16_t *)0x80211040) = 0x0000;   // Burst length=1, Sequential, CL=2, Burst read and burst write

}
#endif

#ifdef USE_HRAM
fsp_err_t hram_init(void)
{
    fsp_err_t err = FSP_SUCCESS;

    /* MDVn pin should be low(Set XSPI operating voltage at 1.8V) */
    uint32_t mdv = (R_SYSC_NS->MD_MON >> 16) & 0x1f;
    if ((0 << MDVn) != (mdv & (1 << MDVn)))
    {
        return FSP_ERR_ABORTED;
    }

    err = g_hyperbus0.p_api->open(g_hyperbus0.p_ctrl, g_hyperbus0.p_cfg);
    while(FSP_SUCCESS != err);

    /* Read HyperRAM register(The data read is big endian.) */
    /* Read setting of identification register 0 */
    volatile hram_transfer_t trans[2];
    trans[0].cmd = HRAM_DEVICE_READ_CMD;
    trans[0].addr = HRAM_DEVICE_ID0_ADDR;
    trans[0].latency = 6;
    trans[0].write = false;
    err = hram_trans(trans[0]);
    while(FSP_SUCCESS != err);
    /* Since the data is big endian, convert the endian and output. */

    /* Read setting of identification register 1 */
    trans[0].addr = HRAM_DEVICE_ID1_ADDR;
    err = hram_trans(trans[0]);
    while(FSP_SUCCESS != err);

    /* Read setting of configuration register 0 */
    trans[0].addr = HRAM_DEVICE_CFG0_ADDR;
    err = hram_trans(trans[0]);
    while(FSP_SUCCESS != err);

    /* Read setting of configuration register 1 */
    trans[0].addr = HRAM_DEVICE_CFG1_ADDR;
    err = hram_trans(trans[0]);
    while(FSP_SUCCESS != err);

    return err;
}

/*******************************************************************************************************************//**
 * Function Name: hram_trans
 * Description  : Transfer HyperRAM
 * Arguments    : hram_transfer_t trans
 * Return Value : fsp_err_t err
 **********************************************************************************************************************/
fsp_err_t hram_trans(hram_transfer_t trans)
{
    fsp_err_t err = FSP_SUCCESS;

    /* xSPI Command Manual Type Buf */
    R_XSPIn->BUF[0].CDT_b.CMDSIZE = 2;  // Command Size: 2 bytes
    R_XSPIn->BUF[0].CDT_b.ADDSIZE = 4;  // Address Size: 4 bytes
    R_XSPIn->BUF[0].CDT_b.DATASIZE = 2; // Write/Read Data Size: 2 bytes
    R_XSPIn->BUF[0].CDT_b.LATE = trans.latency; // Latency cycle
    R_XSPIn->BUF[0].CDT_b.TRTYPE = trans.write; // Transaction Type
    R_XSPIn->BUF[0].CDT_b.CMD = trans.cmd;      // Command (1-2 bytes)
    /* xSPI Command Manual Address Buf */
    R_XSPIn->BUF[0].CDA  = trans.addr;

    /* For write transactions, write data to buffer registers */
    if (true == trans.write)
    {
        R_XSPIn->BUF[0].CDD0 = trans.data;
    }

    /* xSPI Command Manual Control Register 0 */
    R_XSPIn->CDCTL0_b.CSSEL = XSPIn_CS; // Chip select
    R_XSPIn->CDCTL0_b.TRNUM = 0;  // Transaction number: Issue 1 command (using command buffer 0)
    R_XSPIn->CDCTL0_b.PERMD = 0;  // Periodic mode: Direct manual-command mode
    R_XSPIn->CDCTL0_b.PERITV = 0; // Periodic transaction interval: 2 cycles
    FSP_HARDWARE_REGISTER_WAIT(R_XSPIn->CDCTL0_b.TRREQ, 0); // Wait for transaction completion
    R_XSPIn->CDCTL0_b.TRREQ = 1;  // Transaction request: Request transaction
    /* xSPI Interrupt Status Register */
    FSP_HARDWARE_REGISTER_WAIT(R_XSPIn->INTS_b.CMDCMP, 1);  // Wait for requested manual command completion
    /* xSPI Interrupt Clear Register */
    R_XSPIn->INTC_b.CMDCMPC = 1;  // Command Completed interrupt clear: Clear interrupt status

    /* DS Timeout and AHB Bus Error Detection */
    err = check_ints();
    while(FSP_SUCCESS != err)
    {
        return err;
    }

    /* For read transactions, read data from buffer registers. */
    if (false == trans.write)
    {
        trans.data = R_XSPIn->BUF[0].CDD0;
    }

    return err;
}

/*******************************************************************************************************************//**
 * Function Name: check_ints
 * Description  : DS Timeout and AHB Bus Error Detection
 * Arguments    : none
 * Return Value : none
 **********************************************************************************************************************/
fsp_err_t check_ints(void)
{
    /* AHB bus error detection */
    if (R_XSPIn->INTS_b.BUSERR)
    {
        R_XSPIn->INTC_b.BUSERRC = 1;
        return FSP_ERR_ABORTED;
    }
    /* DS timeout detection */
    if (XSPIn_DSTOCS)
    {
        XSPIn_DSTOCS_C = 1;
        return FSP_ERR_ABORTED;
    }

    return FSP_SUCCESS;
}

/*******************************************************************************************************************//**
 * Function Name: swap16
 * Description  : Convert endian
 * Arguments    : uint16_t value
 * Return Value : return ret
 **********************************************************************************************************************/
uint16_t swap16(uint16_t value)
{
    uint16_t ret;
    ret  = value << 8;
    ret |= value >> 8;
    return ret;
}
#endif

void bsp_clear_external_bss_sections(void)
{
    uintptr_t * src;
    uintptr_t   size;

    src  = (uintptr_t *) EXTRAMNC_BLOCK_START;
    size = (uintptr_t) EXTRAMNC_BLOCK_END - (uintptr_t) EXTRAMNC_BLOCK_START;
    bsp_bss_init_multibyte(src, size);

    src  = (uintptr_t *) HEAP_BLOCK_START;
    size = (uintptr_t) HEAP_BLOCK_END - (uintptr_t) HEAP_BLOCK_START;
    bsp_bss_init_multibyte(src, size);

    src  = (uintptr_t *) EXTBSS_BLOCK_START;
    size = (uintptr_t) EXTBSS_BLOCK_END - (uintptr_t) EXTBSS_BLOCK_START;
    bsp_bss_init_multibyte(src, size);
}

void bsp_copy_to_external_ram(void)
{
    /* Define destination/source address pointer and block size */
    uintptr_t * src;
    uintptr_t * dst;
    uintptr_t   size;

    /* Copy user program block */
    src  = (uintptr_t *) SYSTEM_PRG_SRC_START;
    dst  = (uintptr_t *) SYSTEM_PRG_DST_START;
    size = (uintptr_t) SYSTEM_PRG_SIZE;
    bsp_copy_multibyte(src, dst, size);

    /* Copy user data block */
    src  = (uintptr_t *) SYSTEM_DATA_SRC_START;
    dst  = (uintptr_t *) SYSTEM_DATA_DST_START;
    size = (uintptr_t) SYSTEM_DATA_SIZE;
    bsp_copy_multibyte(src, dst, size);
}
